---
# tasks file for nfs
  # if $server_enabled {

    # if $server_nfsv4_servicehelper != undef {
    # see https://stackoverflow.com/questions/40496021/how-to-remove-a-single-key-from-an-ansible-dictionary
    #   $effective_nfsv4_client_services = delete($client_nfsv4_services, $server_nfsv4_servicehelper)
    # } else {
  #     $effective_nfsv4_client_services = $client_nfsv4_services
  #   }

  #   $effective_client_services = $client_services
  #   $effective_client_packages = difference($client_packages, $server_packages)

  # } else {
  #   if $client_gssd_service and $client_gssd_service_name != undef {
  #     $effective_nfsv4_client_services = $client_nfsv4_services + $client_gssd_service_name
  #   } else {
  #     $effective_nfsv4_client_services = $client_nfsv4_services
  #   }

  #   $effective_client_services = $client_services
  #   $effective_client_packages = $client_packages

  # }
- name: "Include {{ ansible_os_family }} os family variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set effective_codename
  ansible.builtin.set_fact:
    effective_codename: focal
  when: ansible_distribution_release in ['jammy', 'focal', 'bionic', 'focal']

- name: "Include dist codename {{ effective_codename }} for debian"
  ansible.builtin.include_vars: "{{ ansible_os_family }}/{{ effective_codename }}.yml"
  when: ansible_os_family == "Debian"

- name: Show variable nfs_server_enabled
  ansible.builtin.debug:
    msg: "nfs_server_enabled: {{ nfs_server_enabled }}"

- name: Include server tasks
  ansible.builtin.include_tasks: server.yml
  when: nfs_server_enabled

- name: Include client tasks
  ansible.builtin.include_tasks: client.yml
  when: nfs_client_enabled
...
