---
# tasks file for ansible-role-nfs
# ref: https://www.howtoforge.com/tutorial/install-nfs-server-and-client-on-debian/
- name: Install nfs client
  ansible.builtin.package:
    name: nfs-common
  when: is_nfs_client

- name: Install nfs server
  when: is_nfs_server
  block:
    - name: Install nfs server kernel
      ansible.builtin.package:
        name: nfs-kernel-server

    - name: Enable service nfs-server, and not touch the state
      ansible.builtin.service:
        name: nfs-server
        enabled: true
      when:
        - not ansible_check_mode

    - name: Set need statd
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-common
        regexp: '^NEED_STATD'
        line: 'NEED_STATD="no"'
      when: is_nfsv4_only
      notify: Restart nfs-server

    - name: Set need idmapd
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-common
        regexp: '^NEED_IDMAPD'
        line: 'NEED_IDMAPD="yes"'
      when: is_nfsv4_only
      notify: Restart nfs-server

    - name: Set nfsv4 server default
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-kernel-server
        regexp: 'RPCNFSDOPTS'
        line: 'RPCNFSDOPTS="-N 2 -N 3"'
      when: is_nfsv4_only
      notify: Restart nfs-server

    - name: Set nfsv4 default
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-kernel-server
        regexp: '^RPCMOUNTDOPTS'
        line: 'RPCMOUNTDOPTS="--manage-gids -N 2 -N 3"'
      when: is_nfsv4_only
      notify: Restart nfs-server
...
