---
- name: Import pre-flight.yml
  ansible.builtin.import_tasks:
    file: pre-flight.yml
  run_once: true
  delegate_to: localhost

- name: Include ntp service tasks
  ansible.builtin.include_tasks: tasks/ntp-service.yml
  when: nfs_manage_ntp

- name: Include the os family variables
  ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Include nfs server tasks
  ansible.builtin.include_tasks: tasks/nfs-server.yml
  when: nfs_server
...
