---
# tasks file for nfs
- name: "Include {{ ansible_os_family }} os family variables"
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Set effective_codename
  ansible.builtin.set_fact:
    effective_codename: focal
  when: ansible_distribution_release in ['jammy', 'focal', 'bionic']

- name: Set effective_codename
  ansible.builtin.set_fact:
    effective_codename: bullseye
  when: ansible_distribution_release in ['bullseye', 'buster', 'stretch', 'xenial', 'yakkety', 'zesty']

- name: "Include dist codename {{ effective_codename }} for debian"
  ansible.builtin.include_vars: "{{ ansible_os_family }}/{{ effective_codename }}.yml"
  when: ansible_os_family == "Debian"

- name: Set effective_client_services
  ansible.builtin.set_fact:
    effective_client_services: "{{ nfs_client_services }}"

- name: Server enabled block
  block:
    - name: Set effective_nfsv4_client_services fact when nfs_server_nfsv4_servicehelper
      ansible.builtin.set_fact:
        effective_nfsv4_client_services: "{{ nfs_client_nfsv4_services | del_by_list(nfs_server_nfsv4_servicehelper) }}"
      when: nfs_server_nfsv4_servicehelper is defined and (nfs_server_nfsv4_servicehelper|length>0)

    - name: Set effective_nfsv4_client_services fact when nfs_server_nfsv4_servicehelper
      ansible.builtin.set_fact:
        effective_nfsv4_client_services: "{{ nfs_client_nfsv4_services }}"
      when: nfs_server_nfsv4_servicehelper is not defined or (nfs_server_nfsv4_servicehelper|length==0)

    - name: Set effective_client_packages
      ansible.builtin.set_fact:
        effective_client_packages: "{{ nfs_client_packages | difference(nfs_server_packages) }}"

    - name: Include server tasks
      ansible.builtin.include_tasks: server.yml

  when: nfs_server_enabled

- name: Server not enabled block
  block:
    - name: Set effective_nfsv4_client_services fact for gssd
      ansible.builtin.set_fact:
        effective_nfsv4_client_services: "{{ nfs_client_nfsv4_services + nfs_client_gssd_service_name }}"
      when:
        - nfs_client_gssd_service is defined
        - nfs_client_gssd_service_name is defined

    - name: Set effective_nfsv4_client_services fact for not gssd
      ansible.builtin.set_fact:
        effective_nfsv4_client_services: "{{ nfs_client_nfsv4_services }}"
      when: nfs_client_gssd_service is not defined or nfs_client_gssd_service_name is not defined

    - name: Set effective_nfsv4_client_services fact when nfs_server_nfsv4_servicehelper
      ansible.builtin.set_fact:
        effective_nfsv4_client_services: "{{ nfs_client_nfsv4_services }}"
      when: nfs_server_nfsv4_servicehelper is not defined

    - name: Set effective_client_packages
      ansible.builtin.set_fact:
        effective_client_packages: "{{ nfs_client_packages }}"

  when: not nfs_server_enabled

- name: Show variable effective_client_services
  ansible.builtin.debug:
    msg: "effective_client_services: {{ effective_client_services }}"

- name: Show variable effective_nfsv4_client_services
  ansible.builtin.debug:
    msg: "effective_nfsv4_client_services: {{ effective_nfsv4_client_services }}"

- name: Include client tasks
  ansible.builtin.include_tasks: client.yml
  when: nfs_client_enabled
...
