---
# client_services_tasks
- name: Show nfs_v4 client services
  ansible.builtin.debug:
    msg: "client_services: {{ effective_nfsv4_client_services }}"
  when: nfs_v4

- name: Show nfs client services
  ansible.builtin.debug:
    msg: "client_services: {{ effective_client_services }}"
  when: not nfs_v4
  
  # see https://stackoverflow.com/questions/42167747/how-to-loop-over-this-dictionary-in-ansible
- name: Client Services Handler block
  block:
  - name: Restart nfs_v4 client services
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
      enable: "{{ nfs_client_services_enable }}"
    loop: "{{ effective_nfsv4_client_services }}"
    when: nfs_v4

  - name: Restart nfs client services
    ansible.builtin.service:
      name: "{{ item }}"
      state: restarted
      enable: "{{ nfs_client_services_enable }}"
    loop: "{{ effective_client_services }}"
    when: not nfs_v4
  when:
    - not ansible_check_mode
    - nfs_manage_client_service
