---
- name: Ensure client packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ nfs_client_packages }}.yml"

- name: Set nfs v4 client options for debian
  when:
    - ansible_os_family == "Debian"
    - nfs_v4_client_only
  block:
    - name: Set need statd
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-common
        regexp: '^NEED_STATD'
        line: 'NEED_STATD="no"'
      notify: Restart nfs-server

    - name: Set need idmapd
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-common
        regexp: '^NEED_IDMAPD'
        line: 'NEED_IDMAPD="yes"'
      notify: Restart nfs-server
...
