---
# tasks file for ansible-role-nfs
# ref: https://www.howtoforge.com/tutorial/install-nfs-server-and-client-on-debian/
- name: Ensure server packages
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ nfs_server_packages }}"

- name: Enable service nfs-server, and not touch the state
  ansible.builtin.service:
    name: nfs-server
    enabled: true
  when:
    - not ansible_check_mode

- name: Include nfs4 server tasks
  ansible.builtin.include_tasks: tasks/nfs4-server.yml
  when: nfs_v4_server_only

# - name: Ensure export config file
#   ansible.builtin.template:
#     src: templates/exports.j2
#     dest: /etc/exports
#     owner: root
#     group: root
#     mode: "0644"
#   notify: Reload exports
...
# vim: ft=yaml
