---

- name: Set nfs v4 client options for debian
  when:
    - ansible_os_family == "Debian"
    - nfs_v4_server_only
  block:
    - name: Set nfsv4 server default
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-kernel-server
        regexp: 'RPCNFSDOPTS'
        line: 'RPCNFSDOPTS="-N 2 -N 3"'
      notify: Restart nfs-server

    - name: Set nfsv4 default
      ansible.builtin.lineinfile:
        path: /etc/default/nfs-kernel-server
        regexp: '^RPCMOUNTDOPTS'
        line: 'RPCMOUNTDOPTS="--manage-gids -N 2 -N 3"'
      notify: Restart nfs-server

- name: Ensure export root directory
  ansible.builtin.file:
    state: directory
    path: "{{ nfs_export_root }}"
    owner: nobody
    group: nogroup
    mode: "0755"

- name: Include bind mounts tasks
  ansible.builtin.include_tasks: tasks/bind-mounts.yml
  loop: "{{ nfs_v4_bind_mounts }}"

- name: Include bind mounts remove tasks
  ansible.builtin.include_tasks: tasks/remove-mounts.yml
  loop: "{{ nfs_v4_bind_mounts_remove }}"
...
